source_path <- Sys.getenv("TVCQGCOMP_SOURCE_DATA", unset = "")
if (!nzchar(source_path)) {
  candidates <- c(
    file.path("..", "..", "tvcQGComp Simulation Paper", "sim.data.RDS"),
    "sim.data.RDS"
  )
  available <- candidates[file.exists(candidates)]
  if (!length(available)) {
    stop(
      "Set TVCQGCOMP_SOURCE_DATA to the original sim.data.RDS file before ",
      "running this script."
    )
  }
  source_path <- available[[1L]]
}

source_data <- as.data.frame(readRDS(source_path))
source_data$TimeOut_numeric <- as.integer(as.character(source_data$TimeOut))

participant_summary <- aggregate(
  cbind(status, TimeOut_numeric) ~ UniqID,
  data = source_data,
  FUN = max
)
names(participant_summary)[names(participant_summary) == "status"] <- "died"
names(participant_summary)[names(participant_summary) == "TimeOut_numeric"] <- "follow_up"

event_pool <- participant_summary[participant_summary$died == 1, ]
survivor_pool <- participant_summary[participant_summary$died == 0, ]

set.seed(20260729L)

# Retain every observed follow-up duration while selecting exactly 100 deaths.
event_anchors <- unlist(lapply(1:13, function(year) {
  sample(event_pool$UniqID[event_pool$follow_up == year], 1L)
}), use.names = FALSE)
event_ids <- c(
  event_anchors,
  sample(setdiff(event_pool$UniqID, event_anchors), 100L - length(event_anchors))
)

survivor_anchors <- unlist(lapply(1:13, function(year) {
  sample(survivor_pool$UniqID[survivor_pool$follow_up == year], 1L)
}), use.names = FALSE)
survivor_ids <- c(
  survivor_anchors,
  sample(
    setdiff(survivor_pool$UniqID, survivor_anchors),
    400L - length(survivor_anchors)
  )
)

selected_ids <- sample(c(event_ids, survivor_ids))
id_map <- setNames(seq_along(selected_ids), selected_ids)

sim_data <- source_data[source_data$UniqID %in% selected_ids, ]
sim_data$UniqID <- unname(id_map[as.character(sim_data$UniqID)])
sim_data$TimeOut_numeric <- NULL
sim_data <- sim_data[order(sim_data$UniqID, sim_data$TimeInn), ]
rownames(sim_data) <- NULL

# The source data contain exposure quartile codes. Add deterministic
# within-quartile variation and map each component to a positive continuous
# scale so the package performs quantization during analysis.
exposure_specs <- list(
  BC = c(offset = 0.50, scale = 0.35),
  NIT = c(offset = 0.80, scale = 0.55),
  SO4 = c(offset = 0.60, scale = 0.45),
  NH4 = c(offset = 0.40, scale = 0.30),
  OM = c(offset = 1.20, scale = 0.80)
)

set.seed(20260730L)
for (exposure in names(exposure_specs)) {
  quantile_code <- as.numeric(sim_data[[exposure]])
  within_quantile <- stats::runif(nrow(sim_data), min = -0.45, max = 0.45)
  spec <- exposure_specs[[exposure]]
  sim_data[[exposure]] <- round(
    spec[["offset"]] + spec[["scale"]] * (quantile_code + within_quantile),
    digits = 4
  )
}

# Lag histories are intentionally absent from the public dataset. They are
# generated by tvcQGComp when auto_history = TRUE.
lag_columns <- grep("_lag[0-9]+$", names(sim_data), value = TRUE)
sim_data[lag_columns] <- NULL

check_summary <- aggregate(
  cbind(status, TimeInn) ~ UniqID,
  data = transform(sim_data, TimeInn = TimeInn + 1L),
  FUN = max
)
stopifnot(
  nrow(check_summary) == 500L,
  sum(check_summary$status) == 100L,
  mean(check_summary$status) == 0.20,
  all(range(check_summary$TimeInn) == c(1, 13)),
  all(sort(unique(check_summary$TimeInn)) == 1:13),
  !any(grepl("_lag[0-9]+$", names(sim_data))),
  all(vapply(
    names(exposure_specs),
    function(exposure) {
      values <- sim_data[[exposure]]
      is.numeric(values) &&
        all(is.finite(values)) &&
        length(unique(values)) > 100L &&
        any(abs(values - round(values)) > 1e-8)
    },
    logical(1)
  ))
)

save(sim_data, file = file.path("data", "sim_data.rda"), compress = "xz", version = 2)
saveRDS(
  sim_data,
  file = file.path("inst", "extdata", "sim_data_500.RDS"),
  compress = "xz",
  version = 2
)

cat(
  "Created sim_data with ", nrow(sim_data), " rows, 500 participants, ",
  "100 deaths (20%), 1-13 years of follow-up, continuous exposures, and ",
  "no precomputed lag columns.\n",
  sep = ""
)
